### ISSUE TITLE
Power on check the system components.

### ISSUE THREAD

**Issue by griswaldbrooks** [cclrobotics/lhr-testing#9]
_From @griswaldbrooks on July 17, 2016 0:0_

Need to verify that the system components work.

Power on checks:
- [x] Raspberry Pi
- [x] Arduino
- [x] Smoothieboard
- [ ] ~~Electrophoresis voltage regulator~~ #12
- [x] OpenPCR
- [x] Centrifuge
- [x] Shaker
- [x] Freezer
- [x] Freezer arduino
- [x] UV Lightbox
- [x] VL Lightbox
- [ ] ~~Incubator~~ Doesn't exist.

_Copied from original issue: cclrobotics/lhr-docs#3_

**Comment by griswaldbrooks** [comment]
Raspberry Pi powered on with issue. Went to boot screen, got password prompt.

**Comment by griswaldbrooks** [comment]
Arduino powers up fine and drivers install on Windows computer.
Shaker and centrifuge turn on fine. None of these were done with their relays.

**Comment by griswaldbrooks** [comment]
Electrophoresis box "powers up" but doesn't work. #12 describes the issue.

**Comment by griswaldbrooks** [comment]
Smoothieboard powers up. Windows recognizes it, though says it needs a different driver.

**Comment by griswaldbrooks** [comment]
The arduino for the freezer is an Arduino Pro Mini.
After plugging it into its power supply, the red power led comes on and the green LED 13 comes on.
It needs an FTDI to communicate with it which we don't have on hand.

**Comment by tamarum** [comment]
Freezer works. Temperature at the bottom of the fridge was -20˚C, near the opening it is -12˚C. Pedro suggested putting a jack in the freezer to raise samples to near the top of the fridge to allow them to thaw. We should look into this in the future.

**Comment by griswaldbrooks** [comment]
Both OpenPCR machines turn on. Both lightboxes power on.

**Comment by griswaldbrooks** [comment]
The incubator cannot be tested. It is most likely just a lightbulb, which we cannot find.
